description:
  This section can be used to setup a captive portal on the AP.
type: object
properties:
  gateway-name:
    description:
      This name will be presented to connecting users in on the splash page.
    type: string
    default: uCentral - Captive Portal
  gateway-fqdn:
    description:
      The fqdn used for the captive portal IP.
    type: string
    format: fqdn
    default: ucentral.splash
  maxclients:
    description:
      The maximum number of clients that shall be accept.
    type: integer
    default: 32
  upload-rate:
    description:
      The maximum upload rate for a specific client.
    type: integer
    default: 10000
  download-rate:
    description:
      The maximum download rate for a specific client.
    type: integer
    default: 10000
  upload-quota:
    description:
      The maximum upload quota for a specific client.
    type: integer
    default : 10000
  download-quota:
    description:
      The maximum download quota for a specific client.
    type: integer
    default: 10000
