description:
  This section describes all of the services that may be present on the AP.
  Each service is then referenced via its name inside an interface, ssid, ...
type: object
properties:
  lldp:
    $ref: "https://ucentral.io/schema/v1/service/lldp/"
  ssh:
    $ref: "https://ucentral.io/schema/v1/service/ssh/"
  ntp:
    $ref: "https://ucentral.io/schema/v1/service/ntp/"
  mdns:
    $ref: "https://ucentral.io/schema/v1/service/mdns/"
  rtty:
    $ref: "https://ucentral.io/schema/v1/service/rtty/"
  log:
    $ref: "https://ucentral.io/schema/v1/service/log/"
  http:
    $ref: "https://ucentral.io/schema/v1/service/http/"
  igmp:
    $ref: "https://ucentral.io/schema/v1/service/igmp/"
  ieee8021x:
    $ref: "https://ucentral.io/schema/v1/service/ieee8021x/"
  radius-proxy:
    $ref: "https://ucentral.io/schema/v1/service/radius-proxy/"
  online-check:
    $ref: "https://ucentral.io/schema/v1/service/online-check/"
  open-flow:
    $ref: "https://ucentral.io/schema/v1/service/open-flow/"
  data-plane:
    $ref: "https://ucentral.io/schema/v1/service/data-plane/"
  wifi-steering:
    $ref: "https://ucentral.io/schema/v1/service/wifi-steering/"
